/*
 * Layout Config
 */
export const SET_MODIFIER_FORM = 'SET_MODIFIER_FORM';

/*
* Analysis Action Types
* */
export const INIT_ANALYSIS = 'INIT_ANALYSIS';
export const SET_OFFER_PRICE = 'SET_OFFER_PRICE';
export const SET_LOAN_AMOUNT = 'SET_LOAN_AMOUNT';
export const SET_DOWN_PAYMENT = 'SET_DOWN_PAYMENT';
export const SET_DOWN_PAYMENT_PERCENT = 'SET_DOWN_PAYMENT_PERCENT';
export const ADD_PURCHASE_COST_ITEM = 'ADD_PURCHASE_COST_ITEM';
export const DELETE_PURCHASE_COST_ITEM = 'DELETE_PURCHASE_COST_ITEM';
export const UPDATE_PURCHASE_COST_ITEM = 'UPDATE_PURCHASE_COST_ITEM';
export const CALC_DOWN_PAYMENT = 'CALC_DOWN_PAYMENT';
export const CALC_LOAN_AMOUNT = 'CALC_LOAN_AMOUNT';
export const CALC_TOTAL_CASH_NEEDED = 'CALC_TOTAL_CASH_NEEDED';
export const CALC_PURCHASE_COSTS = 'CALC_PURCHASE_COSTS';
export const REORDER_ITEMIZED_PURCHASE_COSTS = 'REORDER_ITEMIZED_PURCHASE_COSTS';
